language: python
python:
  - "3.5"
install:
  - pip install python-coveralls
script: 
  - coverage run test_rpn.py
  - coverage report -m
  - nosetests --with-coverage --cover-package=app --cov-report term-missing
after_success:
  - coveralls
